/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EnrollRouteImport } from './routes/enroll'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnrollTestRouteImport } from './routes/enroll.test'

const EnrollRoute = EnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollTestRoute = EnrollTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => EnrollRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/enroll': typeof EnrollRouteWithChildren
  '/enroll/test': typeof EnrollTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/enroll': typeof EnrollRouteWithChildren
  '/enroll/test': typeof EnrollTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/enroll': typeof EnrollRouteWithChildren
  '/enroll/test': typeof EnrollTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/enroll' | '/enroll/test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/enroll' | '/enroll/test'
  id: '__root__' | '/' | '/enroll' | '/enroll/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnrollRoute: typeof EnrollRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/enroll': {
      id: '/enroll'
      path: '/enroll'
      fullPath: '/enroll'
      preLoaderRoute: typeof EnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enroll/test': {
      id: '/enroll/test'
      path: '/test'
      fullPath: '/enroll/test'
      preLoaderRoute: typeof EnrollTestRouteImport
      parentRoute: typeof EnrollRoute
    }
  }
}

interface EnrollRouteChildren {
  EnrollTestRoute: typeof EnrollTestRoute
}

const EnrollRouteChildren: EnrollRouteChildren = {
  EnrollTestRoute: EnrollTestRoute,
}

const EnrollRouteWithChildren =
  EnrollRoute._addFileChildren(EnrollRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnrollRoute: EnrollRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
